server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      sla:
        http:
          server:
            requests: 1ms,5ms,10ms,50ms,100ms,200ms,500ms,1s,5s
    tags:
      application: spring-boot-mvc-demo